from enum import Enum

class Values(Enum):
    NORMALIZATION_COEFFICIENT = 1,
    COERCIVE_FORCE = 2,
    SIGMA = 3,
    INTERDOMAIN_COUPLING = 4,
    DOMAIN_WALLS_DENSITY = 5,
    SATURATION_MAGNETIZATION = 6,
    AVG_ENERGY_TO_BREAK_PINNING_SITE = 7,
    MAGNETIZATION_REVERSIBILITY = 8,
    AVG_ANISOTROPY_ENERGY_DENSITY = 9,
    ANGLE = 10,
    ANISOTROPIC_PARTICIPATION = 11
